import { useState } from 'react'
import WelcomeSection from './WelcomeSection'
import AccountStatus from './AccountStatus'
import StatsChart from './StatsChart'
import KeyActions from './KeyActions'
import LocalSearch from './LocalSearch'
import AIModule from './AIModule'
import './Dashboard.css'

interface User {
  email: string
}

interface DashboardProps {
  user: User
  onLogout: () => void
}

export default function Dashboard({ user, onLogout }: DashboardProps) {
  const [searchResults, setSearchResults] = useState<string[]>([])
  const [aiResults, setAiResults] = useState<any>(null)

  const handleSearch = (query: string) => {
    const mockResults = [
      `Search result for "${query}" - Document 1`,
      `Search result for "${query}" - Document 2`,
      `Search result for "${query}" - User Profile`,
      `Search result for "${query}" - Settings`
    ].filter(result => 
      result.toLowerCase().includes(query.toLowerCase())
    )
    setSearchResults(mockResults)
  }

  const handleAIQuery = async (query: string, outputType: string) => {
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    switch (outputType) {
      case 'text':
        setAiResults({
          type: 'text',
          content: `AI Response: Based on your query "${query}", here is a comprehensive analysis. This would typically be generated by an AI model and could include detailed explanations, insights, and recommendations.`
        })
        break
      case 'histogram':
        setAiResults({
          type: 'histogram',
          content: {
            title: `Histogram Analysis for: ${query}`,
            data: Array.from({ length: 10 }, (_, i) => ({
              name: `Category ${i + 1}`,
              value: Math.floor(Math.random() * 100) + 10
            }))
          }
        })
        break
      case 'fileupload':
        setAiResults({
          type: 'fileupload',
          content: `File upload interface ready for query: "${query}". You can now upload relevant files for processing.`
        })
        break
      default:
        setAiResults({
          type: 'text',
          content: `Processing query "${query}" with output type "${outputType}"`
        })
    }
  }

  return (
    <div className="dashboard">
      <div className="dashboard-container">
        <div className="dashboard-header">
          <WelcomeSection user={user} />
          <button className="logout-button" onClick={onLogout}>
            <span className="logout-icon">🚪</span>
            Logout
          </button>
        </div>

        <div className="dashboard-grid">
          <div className="dashboard-row">
            <div className="dashboard-card account-status-card">
              <AccountStatus user={user} />
            </div>
            <div className="dashboard-card key-actions-card">
              <KeyActions />
            </div>
          </div>

          <div className="dashboard-row">
            <div className="dashboard-card stats-card">
              <StatsChart />
            </div>
          </div>

          <div className="dashboard-row">
            <div className="dashboard-card search-card">
              <LocalSearch 
                onSearch={handleSearch} 
                results={searchResults}
              />
            </div>
            <div className="dashboard-card ai-module-card">
              <AIModule 
                onQuery={handleAIQuery}
                results={aiResults}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
